apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: onpremlr
  region: us-east-1
  version: "1.21"
  tags:
    karpenter.sh/discovery: onpremlr
managedNodeGroups:
  - instanceType: m5.xlarge
    amiFamily: AmazonLinux2
    name: runner-nodes
    desiredCapacity: 3
    minSize: 2
    maxSize: 5
iam:
  withOIDC: true
